import { useEffect, useMemo, useRef, useState } from "react";
import type { GameDefinition } from "../config/games";
import { championProbabilities, clampScore, energyTotal, fireSpreadFrames, hospitalImpact, optimalKnapsack, type FireCell } from "../game/common";
import { CommonResult } from "./CommonResult";
import { RaceStrategyGame } from "./RaceStrategyGame";

type Result = { score: number; title: string; metrics: Array<[string, string | number]>; explanation: string };
const fireBoard: FireCell[][] = [["forest","forest","nature","home","home"],["fire","forest","forest","forest","home"],["forest","nature","forest","forest","forest"],["nature","nature","forest","home","home"]];
const teams = [{ name: "Cóndores", attack: 92, defense: 72, form: 84 }, { name: "Pumas", attack: 76, defense: 90, form: 79 }, { name: "Faros", attack: 82, defense: 80, form: 91 }, { name: "Volcanes", attack: 88, defense: 69, form: 73 }];
const services = [{ name: "Hospital", icon: "🏥", consumption: 32, essential: true }, { name: "Viviendas", icon: "🏘️", consumption: 24, essential: true }, { name: "Alumbrado", icon: "💡", consumption: 14, essential: false }, { name: "Escuela", icon: "🏫", consumption: 12, essential: false }, { name: "Comercio", icon: "🏪", consumption: 18, essential: false }, { name: "Transporte", icon: "🚇", consumption: 20, essential: true }];
const spaceItems = [{ name: "Oxígeno", icon: "🫧", weight: 5, utility: 10 }, { name: "Robot", icon: "🤖", weight: 7, utility: 12 }, { name: "Panel solar", icon: "☀️", weight: 6, utility: 11 }, { name: "Kit científico", icon: "🧪", weight: 4, utility: 8 }, { name: "Antena", icon: "📡", weight: 3, utility: 7 }, { name: "Alimentos", icon: "🥫", weight: 5, utility: 9 }, { name: "Cámara", icon: "📷", weight: 2, utility: 4 }, { name: "Herramientas", icon: "🧰", weight: 6, utility: 8 }];
const hospitals = [{ name: "Hospital Norte", waiting: 28, beds: 5, staff: 9 }, { name: "Hospital Centro", waiting: 42, beds: 2, staff: 4 }, { name: "Hospital Sur", waiting: 24, beds: 9, staff: 12 }];

function useDelayedFinish(finish: (result: Result) => void) {
  const timeout = useRef<number | null>(null);
  useEffect(() => () => { if (timeout.current !== null) window.clearTimeout(timeout.current); }, []);
  return (result: Result, delay: number) => { timeout.current = window.setTimeout(() => finish(result), delay); };
}

export function EducationalGame({ game, onHome }: { game: GameDefinition; onHome: () => void }) {
  const [run, setRun] = useState(0);
  const [result, setResult] = useState<Result | null>(null);
  const reset = () => { setResult(null); setRun(value => value + 1); };
  return <main className="mini-game" key={run}>
    <div className="game-progress" aria-hidden="true"><span /></div>
    <section className="game-intro"><div className="game-icon">{game.icon}</div><div><p className="eyebrow">{game.duration} · {game.categories.join(" · ")}</p><h1>{game.title}</h1><p>{game.fullDescription}</p></div></section>
    {result ? <CommonResult {...result} learning={game.learning} onAgain={reset} onHome={onHome} /> : <GameBody game={game} finish={setResult} />}
  </main>;
}

function GameBody({ game, finish }: { game: GameDefinition; finish: (result: Result) => void }) {
  if (game.id === "incendio") return <FireGame finish={finish} />;
  if (game.id === "formula-1") return <RaceStrategyGame finish={finish} />;
  if (game.id === "detective-datos") return <DetectiveGame finish={finish} />;
  if (game.id === "campeon") return <ChampionGame finish={finish} />;
  if (game.id === "energia") return <EnergyGame finish={finish} />;
  if (game.id === "esperar") return <WaitingGame finish={finish} />;
  if (game.id === "vivienda") return <HousingGame finish={finish} />;
  if (game.id === "mision-espacial") return <SpaceGame finish={finish} />;
  return <HospitalGame finish={finish} />;
}

function FireGame({ finish }: { finish: (result: Result) => void }) {
  const [breaks, setBreaks] = useState(new Set<string>());
  const [simulating, setSimulating] = useState(false);
  const [burning, setBurning] = useState(new Set(["0,1"]));
  const [wave, setWave] = useState(0);
  const finishAfter = useDelayedFinish(finish);
  const timers = useRef<number[]>([]);
  useEffect(() => () => timers.current.forEach(window.clearTimeout), []);
  const toggle = (key: string) => setBreaks(current => { const next = new Set(current); if (next.has(key)) next.delete(key); else if (next.size < 4) next.add(key); return next; });
  const simulate = () => { setSimulating(true); const frames=fireSpreadFrames(fireBoard,breaks,6); frames.forEach((frame,index)=>timers.current.push(window.setTimeout(()=>{setBurning(frame);setWave(index);},index*620))); const burned=frames[frames.length-1]; let homes=0,nature=0;fireBoard.forEach((row,y)=>row.forEach((cell,x)=>{if(!burned.has(`${x},${y}`)&&cell==="home")homes++;if(!burned.has(`${x},${y}`)&&cell==="nature")nature++;}));const score=clampScore(420+homes*80+nature*55);finishAfter({score,title:score>=800?"Buena ubicación":"Prueba otra estrategia",metrics:[["Viviendas protegidas",homes],["Áreas naturales protegidas",nature],["Superficie afectada",`${burned.size} zonas`],["Referencia","4 cortafuegos bien distribuidos"]],explanation:"Viste la propagación por oleadas: cada cortafuego cortó conexiones y cambió el frente del incendio."},frames.length*620+700); };
  return <section className={`play-panel fire-simulation ${simulating ? "running" : ""}`}><div className="panel-heading"><div><h2>{simulating?`Frente de fuego · minuto ${wave+1}`:"Ubica 4 cortafuegos"}</h2><p>{simulating?"El viento empuja las llamas hacia el este →":"Viento hacia el este →. Selecciona celdas antes de iniciar."}</p></div><span>{simulating?`🔥 ${burning.size}`:`${breaks.size}/4`}</span></div><div className="wind-stream" aria-hidden="true"><i/><i/><i/><span>VIENTO</span></div><div className="fire-board">{fireBoard.flatMap((row,y)=>row.map((cell,x)=>{const key=`${x},${y}`;const isBurning=burning.has(key);return <button type="button" disabled={simulating} aria-label={`${cell}, ${breaks.has(key)?"con":"sin"} cortafuego`} className={`${cell} ${breaks.has(key)?"firebreak":""} ${simulating&&isBurning?"burning":""} ${simulating&&!isBurning?"protected":""}`} onClick={()=>cell!=="fire"&&toggle(key)} key={key}>{breaks.has(key)?"🧱":isBurning?"🔥":cell==="home"?"🏠":cell==="nature"?"🦌":"🌲"}<small>{isBurning&&simulating?"Afectada":breaks.has(key)?"Bloqueo":""}</small></button>;}))}</div><div className="fire-legend"><span>🔥 Frente activo</span><span>🧱 Cortafuego</span><span>✨ Zona protegida</span></div><div className="decision-footer"><span>{simulating?`Propagación ${Math.min(100,Math.round((wave+1)/6*100))}%`:`${4-breaks.size} piezas disponibles`}</span><button className="primary" disabled={breaks.size<3||simulating} onClick={simulate}>{simulating?"Simulando expansión…":"Iniciar simulación"}</button></div></section>;
}

function DetectiveGame({ finish }: { finish: (result: Result) => void }) {
  const levels=[{items:["●","●","■","●","●"],odd:2,clue:"La forma no coincide"},{items:["▲","▲","▲","△","▲"],odd:3,clue:"El relleno es diferente"},{items:["◆","◆","◈","◆","◆"],odd:2,clue:"Combina borde y centro"}];
  const [level,setLevel]=useState(0);const [correct,setCorrect]=useState(0);const [selected,setSelected]=useState<number|null>(null);const [feedback,setFeedback]=useState<"correct"|"wrong"|null>(null);const started=useMemo(()=>Date.now(),[]);const timer=useRef<number|null>(null);useEffect(()=>()=>{if(timer.current!==null)clearTimeout(timer.current);},[]);
  const choose=(index:number)=>{if(feedback)return;const hit=index===levels[level].odd;const next=correct+(hit?1:0);setSelected(index);setFeedback(hit?"correct":"wrong");timer.current=window.setTimeout(()=>{if(level===2){const seconds=Math.max(1,Math.round((Date.now()-started)/1000));finish({score:clampScore(next*300+Math.max(0,100-seconds*4)),title:next===3?"Patrones detectados":"Sigue observando",metrics:[["Respuestas correctas",`${next}/3`],["Tiempo",`${seconds}s`],["Anomalía","Forma, relleno y combinación"]],explanation:"El escáner comparó características y destacó por qué una observación se alejaba del patrón."});}else{setCorrect(next);setLevel(value=>value+1);setSelected(null);setFeedback(null);}},750);};
  return <section className={`play-panel detective-simulation ${feedback?`feedback-${feedback}`:""}`}><div className="detective-header"><div><small>ANÁLISIS DE ANOMALÍAS</small><h2>Nivel {level+1} de 3</h2></div><div className="detective-progress">{levels.map((_,index)=><span className={index<level?"complete":index===level?"active":""} key={index}/>)}</div></div><p>El escáner está comparando forma, tamaño y relleno. Selecciona la anomalía.</p><div className="scanner-area"><div className="scanner-beam" aria-hidden="true"/><div className="pattern-grid">{levels[level].items.map((value,index)=><button type="button" disabled={feedback!==null} className={selected===index?feedback??"":""} key={index} onClick={()=>choose(index)} aria-label={`Elemento ${index+1}`}>{value}<small>#{index+1}</small></button>)}</div></div>{feedback&&<div className="analysis-feedback" aria-live="polite"><strong>{feedback==="correct"?"✓ Patrón detectado":"↗ Era otro elemento"}</strong><span>{levels[level].clue}</span></div>}</section>;
}

function ChampionGame({ finish }: { finish: (result: Result) => void }) {
  const probabilities=championProbabilities(teams);const [selected,setSelected]=useState<number|null>(null);const [simulating,setSimulating]=useState(false);const [runs,setRuns]=useState(0);const finishAfter=useDelayedFinish(finish);const interval=useRef<number|null>(null);useEffect(()=>()=>{if(interval.current!==null)clearInterval(interval.current);},[]);
  const simulate=()=>{if(selected===null)return;setSimulating(true);setRuns(0);interval.current=window.setInterval(()=>setRuns(value=>{const next=Math.min(100,value+4);if(next===100&&interval.current!==null){clearInterval(interval.current);interval.current=null;const best=probabilities.indexOf(Math.max(...probabilities));finishAfter({score:selected===best?1000:720,title:selected===best?"Buena predicción":"Una alternativa era más probable",metrics:[["Equipo elegido",teams[selected].name],...teams.map((team,i)=>[team.name,`${probabilities[i]} victorias de 100`] as [string,string])],explanation:"Viste cómo las probabilidades se estabilizaron al repetir el torneo 100 veces."},900);}return next;}),32);};
  return <section className="play-panel champion-simulation"><div className="panel-heading"><div><h2>{simulating?"Torneos en ejecución":"Elige al posible campeón"}</h2><p>{simulating?"Cada punto representa un torneo posible.":"Compara los indicadores antes de predecir."}</p></div><span>{simulating?runs:"🏆"}</span></div><div className="team-grid">{teams.map((team,index)=><button type="button" disabled={simulating} aria-pressed={selected===index} className={selected===index?"selected":""} onClick={()=>setSelected(index)} key={team.name}><strong>{team.name}</strong><span>Ataque {team.attack}</span><span>Defensa {team.defense}</span><span>Forma {team.form}</span></button>)}</div>{simulating&&<div className="simulation-bars" aria-live="polite">{teams.map((team,index)=><div key={team.name}><span>{team.name}</span><div><i style={{width:`${probabilities[index]*runs/100}%`}}/></div><strong>{Math.round(probabilities[index]*runs/100)}</strong></div>)}</div>}<div className="decision-footer"><span>{simulating?`${runs} de 100 torneos simulados`:selected===null?"Selecciona un equipo":`${teams[selected].name} es tu predicción`}</span><button className="primary" disabled={selected===null||simulating} onClick={simulate}>{simulating?"Calculando probabilidades…":"Simular 100 torneos"}</button></div></section>;
}

function EnergyGame({ finish }: { finish: (result: Result) => void }) {
  const phases=[{time:"08:00",name:"Inicio del día",icon:"🌅",multiplier:.75,capacity:100,note:"La demanda comienza a subir."},{time:"13:00",name:"Hora de mayor actividad",icon:"☀️",multiplier:1,capacity:100,note:"Escuela y comercio están activos."},{time:"19:00",name:"Alerta de suministro",icon:"⚠️",multiplier:1.1,capacity:85,note:"Una falla reduce la energía disponible."},{time:"23:00",name:"Demanda nocturna",icon:"🌙",multiplier:.85,capacity:92,note:"Prioriza hospital, viviendas y alumbrado."}];
  const [active,setActive]=useState(()=>services.map(()=>true));const [phase,setPhase]=useState(0);const [safePhases,setSafePhases]=useState(0);const [essentialSum,setEssentialSum]=useState(0);const [transitioning,setTransitioning]=useState(false);const finishAfter=useDelayedFinish(finish);const phaseTimer=useRef<number|null>(null);useEffect(()=>()=>{if(phaseTimer.current!==null)clearTimeout(phaseTimer.current);},[]);const current=phases[phase];const base=energyTotal(services.map((service,index)=>({consumption:service.consumption,active:active[index]})));const total=Math.round(base*current.multiplier);const essentials=services.filter((service,index)=>service.essential&&active[index]).length;const overloaded=total>current.capacity;
  const advance=()=>{const nextSafe=safePhases+(overloaded?0:1);const nextEssential=essentialSum+essentials;setSafePhases(nextSafe);setEssentialSum(nextEssential);setTransitioning(true);if(phase===phases.length-1){const score=clampScore(nextSafe*145+nextEssential*35);finishAfter({score,title:nextSafe===4&&nextEssential>=11?"Ciudad estable todo el día":"Hubo decisiones que ajustar",metrics:[["Periodos sin apagón",`${nextSafe}/4`],["Servicios esenciales",`${nextEssential}/12`],["Energía final",`${total}/${current.capacity}`],["Evento crítico","Reducción a 85 unidades"]],explanation:"La simulación recorrió cuatro horarios y mostró cómo cambian demanda y capacidad durante el día."},900);}else phaseTimer.current=window.setTimeout(()=>{setPhase(value=>value+1);setTransitioning(false);},600);};
  return <section className={`play-panel energy-simulation phase-${phase} ${transitioning?"transitioning":""}`}><div className="energy-dayline">{phases.map((item,index)=><div className={index<phase?"complete":index===phase?"current":""} key={item.time}><span>{item.icon}</span><strong>{item.time}</strong></div>)}</div><div className="panel-heading"><div><small>{current.time} · {current.name}</small><h2>Mantén la ciudad funcionando</h2><p>{current.note}</p></div><span>{current.icon}</span></div><div className="city-simulation" aria-label="Estado energético de la ciudad">{services.map((service,index)=><div className={active[index]?"lit":"off"} key={service.name}><span>{service.icon}</span><small>{service.name}</small><i/></div>)}<div className={`power-grid ${overloaded?"overload":""}`}>⚡</div></div><div className={`energy-meter ${overloaded?"over":""}`}><span style={{width:`${Math.min(100,total/current.capacity*100)}%`}}/><strong>{total} / {current.capacity} unidades</strong></div>{overloaded&&<p className="energy-alert" aria-live="polite">⚠️ Sobrecarga: reduce al menos {total-current.capacity} unidades para evitar el apagón.</p>}<div className="service-grid">{services.map((service,index)=><button type="button" disabled={transitioning} aria-pressed={active[index]} className={active[index]?"active":""} key={service.name} onClick={()=>setActive(values=>values.map((value,i)=>i===index?!value:value))}><span>{service.icon}</span><strong>{service.name}</strong><small>{Math.round(service.consumption*current.multiplier)} u · {service.essential?"Esencial":"Flexible"}</small></button>)}</div><div className="decision-footer"><span>{essentials}/3 servicios esenciales activos</span><button className="primary" disabled={overloaded||transitioning} onClick={advance}>{transitioning?"Avanzando el reloj…":phase===3?"Finalizar el día":`Avanzar a ${phases[phase+1].time}`}</button></div></section>;
}

function WaitingGame({ finish }: { finish:(result:Result)=>void }) { const options=[42,67,54,88,73,96,61]; const [index,setIndex]=useState(0);const [rejected,setRejected]=useState<number[]>([]);const [leaving,setLeaving]=useState(false);const timer=useRef<number|null>(null);useEffect(()=>()=>{if(timer.current!==null)clearTimeout(timer.current);},[]);const accept=()=>{const value=options[index],best=Math.max(...options);finish({score:clampScore(value/best*1000),title:value===best?"Elegiste la mejor opción":"Decisión tomada",metrics:[["Alternativa elegida",`${value} puntos`],["Mejor alternativa",`${best} puntos`],["Momento",`${index+1} de ${options.length}`],["Diferencia",best-value]],explanation:"La cinta de opciones mostró lo que dejaste atrás: esperar abre posibilidades, pero elimina alternativas anteriores."});};const wait=()=>{setLeaving(true);timer.current=window.setTimeout(()=>{setRejected(values=>[...values,options[index]]);setIndex(value=>value+1);setLeaving(false);},420);};return <section className="play-panel centered waiting-simulation"><div className="step-dots" aria-label={`Opción ${index+1} de ${options.length}`}>{options.map((_,step)=><span className={step<=index?"active":""} key={step}/>)}</div><h2>Proyecto {index+1} de {options.length}</h2><p>Solo puedes mirar hacia adelante. Una opción rechazada no vuelve.</p><div className="decision-conveyor"><div className={`option-reveal ${leaving?"leaving":""}`} key={index}>🤖<strong>{options[index]}</strong><span>puntos de potencial</span></div></div>{rejected.length>0&&<div className="rejected-trail"><small>OPCIONES RECHAZADAS</small><div>{rejected.map((value,item)=><span key={item}>✕ {value}</span>)}</div></div>}<div className="action-row"><button className="primary" disabled={leaving} onClick={accept}>Aceptar esta opción</button><button className="secondary" disabled={index===options.length-1||leaving} onClick={wait}>{leaving?"Dejando atrás…":"Seguir esperando"}</button></div></section>; }

function HousingGame({ finish }: { finish:(result:Result)=>void }) { const [value,setValue]=useState(500);const [analyzing,setAnalyzing]=useState(false);const [factor,setFactor]=useState(0);const model=640;const finishAfter=useDelayedFinish(finish);const interval=useRef<number|null>(null);useEffect(()=>()=>{if(interval.current!==null)clearInterval(interval.current);},[]);const submit=()=>{setAnalyzing(true);interval.current=window.setInterval(()=>setFactor(current=>{const next=Math.min(5,current+1);if(next===5&&interval.current!==null){clearInterval(interval.current);interval.current=null;const diff=Math.abs(value-model);finishAfter({score:clampScore(1000-diff*2.4),title:diff<=50?"Estimación muy cercana":"El modelo estimó otro rango",metrics:[["Tu estimación",`${value} unidades`],["Modelo",`${model} unidades`],["Diferencia",`${diff} unidades`],["Variables clave","Tamaño y transporte"]],explanation:"Viste cómo el modelo incorporó cada variable antes de producir la estimación."},700);}return next;}),320);};const factors=[["Tamaño",88],["Transporte",78],["Habitaciones",62],["Áreas verdes",48],["Conservación",70]] as const;return <section className={`play-panel housing-simulation ${analyzing?"analyzing":""}`}><div className="panel-heading"><div><h2>{analyzing?"El modelo está analizando…":"Estima esta vivienda ficticia"}</h2><p>{analyzing?`${factor} de 5 variables procesadas`:"Ajusta el valor antes de consultar al modelo."}</p></div><span>🏠</span></div><div className="house-lab"><div className="house-visual">🏠<i/><b/></div><ul><li>120 m² · 3 habitaciones</li><li>Transporte a 5 minutos</li><li>Áreas verdes cercanas</li><li>Centro a 8 km · Buen estado</li></ul>{analyzing&&<div className="model-scan"/>}</div>{analyzing?<div className="factor-analysis">{factors.map(([name,weight],index)=><div className={index<factor?"processed":""} key={name}><span>{index<factor?"✓":"○"} {name}</span><div><i style={{width:index<factor?`${weight}%`:"0%"}}/></div><strong>{index<factor?`${weight}%`:"…"}</strong></div>)}</div>:<label className="price-slider">Tu estimación: <strong>{value} unidades</strong><input type="range" min="300" max="900" step="10" value={value} onChange={event=>setValue(Number(event.target.value))}/></label>}<button className="primary" disabled={analyzing} onClick={submit}>{analyzing?"Combinando variables…":"Comparar con el modelo"}</button></section>; }

function SpaceGame({ finish }: { finish:(result:Result)=>void }) {
  const [participantTotal,setParticipantTotal]=useState<number | null>(null); const [participant,setParticipant]=useState(1); const [proposals,setProposals]=useState<Array<Set<number>>>([]); const [selected,setSelected]=useState(new Set<number>());const [launching,setLaunching]=useState(false);const finishAfter=useDelayedFinish(finish);
  const consensus=participantTotal !== null && participant>participantTotal; const weight=[...selected].reduce((sum,index)=>sum+spaceItems[index].weight,0); const utility=[...selected].reduce((sum,index)=>sum+spaceItems[index].utility,0); const optimum=optimalKnapsack(spaceItems,25);
  const toggle=(index:number)=>setSelected(current=>{const next=new Set(current);next.has(index)?next.delete(index):next.add(index);return next;});
  const confirm=()=>{setProposals(current=>[...current,new Set(selected)]);setSelected(new Set());setParticipant(value=>value+1);};
  const submit=()=>{const individualUtilities=proposals.map(proposal=>[...proposal].reduce((sum,index)=>sum+spaceItems[index].utility,0));const bestIndividual=Math.max(...individualUtilities);setLaunching(true);finishAfter({score:clampScore(utility/optimum*1000),title:utility>=bestIndividual?"El consenso mejoró la decisión":"La mejor propuesta individual era superior",metrics:[["Peso utilizado",`${weight}/25`],["Utilidad grupal",utility],["Mejor decisión individual",bestIndividual],["Solución óptima",optimum]],explanation:`La nave despegó con una carga válida. El consenso ${utility>=bestIndividual?"mejoró o igualó":"empeoró"} la mejor propuesta individual.`},1800);};
  if (participantTotal === null) return <section className="play-panel"><h2>¿Cuántas personas participan?</h2><p>Las decisiones individuales permanecerán ocultas hasta comenzar el consenso.</p><div className="participant-options">{[2,3,4,5].map(total=><button className="secondary" type="button" onClick={()=>setParticipantTotal(total)} key={total}>{total} participantes</button>)}</div></section>;
  return <section className={`play-panel space-simulation ${launching?"launching":""}`}><div className="space-scene" aria-label="Nave y carga seleccionada"><div className="stars-layer">✦ · ✧ · ✦ · ✧</div><div className="rocket">🚀<div className="cargo-window">{[...selected].slice(0,5).map(index=><span key={index}>{spaceItems[index].icon}</span>)}</div></div><div className="launch-pad"/><div className="rocket-flame">🔥</div></div><h2>{launching?"¡Despegue autorizado!":consensus?"Etapa 2: decisión por consenso":`Etapa 1: participante ${participant} de ${participantTotal}`}</h2><p>{launching?"La nave está verificando peso, utilidad y estabilidad.":consensus?"Las propuestas ya están visibles. Conversen y creen la carga final.":"Elige en privado y confirma. La selección se ocultará antes del siguiente turno."} {!launching&&<>Capacidad restante: <strong>{25-weight}</strong></>}</p>
    {consensus&&<div className="proposal-summary">{proposals.map((proposal,index)=><span key={index}>Propuesta {index+1}: {[...proposal].map(item=>spaceItems[item].name).join(", ")}</span>)}</div>}
    <div className="cargo-meter"><span style={{width:`${Math.min(100,weight/25*100)}%`}}/><strong>{weight}/25 kg</strong></div><div className="space-grid">{spaceItems.map((item,index)=><button type="button" disabled={launching} aria-pressed={selected.has(index)} className={selected.has(index)?"selected":""} onClick={()=>toggle(index)} key={item.name}><span>{item.icon}</span><strong>{item.name}</strong><small>{item.weight} kg · utilidad {item.utility}</small></button>)}</div>
    <button className="primary" disabled={weight>25||selected.size===0||launching} onClick={consensus?submit:confirm}>{launching?"Despegando…":weight>25?"Exceso de peso":consensus?"Despegar":"Confirmar y ocultar"}</button></section>;
}

function HospitalGame({ finish }: { finish:(result:Result)=>void }) { const impacts=hospitals.map(hospitalImpact);const best=impacts.indexOf(Math.max(...impacts));const [selected,setSelected]=useState<number|null>(null);const [dispatching,setDispatching]=useState(false);const finishAfter=useDelayedFinish(finish);const choose=()=>{if(selected===null)return;setDispatching(true);finishAfter({score:selected===best?1000:680,title:selected===best?"Recurso bien asignado":"Había una alternativa de mayor impacto",metrics:[["Hospital seleccionado",hospitals[selected].name],["Personas atendidas",impacts[selected]],["Presión inicial",`${hospitals[selected].waiting} esperando`],["Mejor alternativa",hospitals[best].name]],explanation:"El recurso recorrió la red y mostró el impacto resultante según demanda, camas y personal."},1500);};return <section className={`play-panel hospital-simulation ${dispatching?"dispatching":""}`}><div className="panel-heading"><div><h2>{dispatching?"Unidad de apoyo en camino":"Asigna una unidad de apoyo"}</h2><p>{dispatching?`Destino: ${hospitals[selected!].name}`:"Busca dónde podrá atender a más personas."}</p></div><span>🚑</span></div><div className="hospital-map"><div className="dispatch-center">📦<small>Recurso</small></div><div className="route-line"><i/></div>{hospitals.map((hospital,index)=><button type="button" disabled={dispatching} aria-pressed={selected===index} className={selected===index?"selected":""} onClick={()=>setSelected(index)} key={hospital.name}><span>🏥</span><strong>{hospital.name}</strong><div className="pressure-bar"><i style={{width:`${Math.min(100,hospital.waiting/(hospital.beds+hospital.staff)*18)}%`}}/></div><small>{hospital.waiting} esperando · {hospital.beds} camas · {hospital.staff} personas</small></button>)}{dispatching&&<div className={`moving-unit destination-${selected}`}>🚑</div>}</div><div className="decision-footer"><span>{selected===null?"Unidad disponible":dispatching?"Calculando impacto…":`Destino: ${hospitals[selected].name}`}</span><button className="primary" disabled={selected===null||dispatching} onClick={choose}>{dispatching?"Despachando…":"Asignar recurso"}</button></div></section>; }
