import { useEffect, useMemo, useRef, useState } from "react";
import type { GameDefinition } from "../config/games";
import { championProbabilities, clampScore, energyTotal, hospitalImpact, optimalKnapsack, spreadFire, type FireCell } from "../game/common";
import { CommonResult } from "./CommonResult";
import { RaceStrategyGame } from "./RaceStrategyGame";

type Result = { score: number; title: string; metrics: Array<[string, string | number]>; explanation: string };
const fireBoard: FireCell[][] = [["forest","forest","nature","home","home"],["fire","forest","forest","forest","home"],["forest","nature","forest","forest","forest"],["nature","nature","forest","home","home"]];
const teams = [{ name: "Cóndores", attack: 92, defense: 72, form: 84 }, { name: "Pumas", attack: 76, defense: 90, form: 79 }, { name: "Faros", attack: 82, defense: 80, form: 91 }, { name: "Volcanes", attack: 88, defense: 69, form: 73 }];
const services = [{ name: "Hospital", icon: "🏥", consumption: 32, essential: true }, { name: "Viviendas", icon: "🏘️", consumption: 24, essential: true }, { name: "Alumbrado", icon: "💡", consumption: 14, essential: false }, { name: "Escuela", icon: "🏫", consumption: 12, essential: false }, { name: "Comercio", icon: "🏪", consumption: 18, essential: false }, { name: "Transporte", icon: "🚇", consumption: 20, essential: true }];
const spaceItems = [{ name: "Oxígeno", icon: "🫧", weight: 5, utility: 10 }, { name: "Robot", icon: "🤖", weight: 7, utility: 12 }, { name: "Panel solar", icon: "☀️", weight: 6, utility: 11 }, { name: "Kit científico", icon: "🧪", weight: 4, utility: 8 }, { name: "Antena", icon: "📡", weight: 3, utility: 7 }, { name: "Alimentos", icon: "🥫", weight: 5, utility: 9 }, { name: "Cámara", icon: "📷", weight: 2, utility: 4 }, { name: "Herramientas", icon: "🧰", weight: 6, utility: 8 }];
const hospitals = [{ name: "Hospital Norte", waiting: 28, beds: 5, staff: 9 }, { name: "Hospital Centro", waiting: 42, beds: 2, staff: 4 }, { name: "Hospital Sur", waiting: 24, beds: 9, staff: 12 }];

function useDelayedFinish(finish: (result: Result) => void) {
  const timeout = useRef<number | null>(null);
  useEffect(() => () => { if (timeout.current !== null) window.clearTimeout(timeout.current); }, []);
  return (result: Result, delay: number) => { timeout.current = window.setTimeout(() => finish(result), delay); };
}

export function EducationalGame({ game, onHome }: { game: GameDefinition; onHome: () => void }) {
  const [run, setRun] = useState(0);
  const [result, setResult] = useState<Result | null>(null);
  const reset = () => { setResult(null); setRun(value => value + 1); };
  return <main className="mini-game" key={run}>
    <div className="game-progress" aria-hidden="true"><span /></div>
    <section className="game-intro"><div className="game-icon">{game.icon}</div><div><p className="eyebrow">{game.duration} · {game.categories.join(" · ")}</p><h1>{game.title}</h1><p>{game.fullDescription}</p></div></section>
    {result ? <CommonResult {...result} learning={game.learning} onAgain={reset} onHome={onHome} /> : <GameBody game={game} finish={setResult} />}
  </main>;
}

function GameBody({ game, finish }: { game: GameDefinition; finish: (result: Result) => void }) {
  if (game.id === "incendio") return <FireGame finish={finish} />;
  if (game.id === "formula-1") return <RaceStrategyGame finish={finish} />;
  if (game.id === "detective-datos") return <DetectiveGame finish={finish} />;
  if (game.id === "campeon") return <ChampionGame finish={finish} />;
  if (game.id === "energia") return <EnergyGame finish={finish} />;
  if (game.id === "esperar") return <WaitingGame finish={finish} />;
  if (game.id === "vivienda") return <HousingGame finish={finish} />;
  if (game.id === "mision-espacial") return <SpaceGame finish={finish} />;
  return <HospitalGame finish={finish} />;
}

function FireGame({ finish }: { finish: (result: Result) => void }) {
  const [breaks, setBreaks] = useState(new Set<string>());
  const [simulating, setSimulating] = useState(false);
  const finishAfter = useDelayedFinish(finish);
  const toggle = (key: string) => setBreaks(current => { const next = new Set(current); if (next.has(key)) next.delete(key); else if (next.size < 4) next.add(key); return next; });
  const simulate = () => { setSimulating(true); const burned = spreadFire(fireBoard, breaks); let homes = 0, nature = 0; fireBoard.forEach((row,y) => row.forEach((cell,x) => { if (!burned.has(`${x},${y}`) && cell === "home") homes++; if (!burned.has(`${x},${y}`) && cell === "nature") nature++; })); const score = clampScore(420 + homes * 80 + nature * 55); finishAfter({ score, title: score >= 800 ? "Buena ubicación" : "Prueba otra estrategia", metrics: [["Viviendas protegidas", homes],["Áreas naturales protegidas", nature],["Superficie afectada", `${burned.size} zonas`],["Referencia", "4 cortafuegos bien distribuidos"]], explanation: "El fuego avanzó por celdas vecinas y se detuvo donde instalaste barreras." }, 850); };
  return <section className={`play-panel ${simulating ? "is-simulating" : ""}`}><div className="panel-heading"><div><h2>Ubica 4 cortafuegos</h2><p>Viento hacia el este →. Selecciona celdas antes de iniciar.</p></div><span>{breaks.size}/4</span></div><div className="fire-board">{fireBoard.flatMap((row,y) => row.map((cell,x) => { const key=`${x},${y}`; return <button type="button" disabled={simulating} aria-label={`${cell}, ${breaks.has(key) ? "con" : "sin"} cortafuego`} className={`${cell} ${breaks.has(key) ? "firebreak" : ""}`} onClick={() => cell !== "fire" && toggle(key)} key={key}>{breaks.has(key) ? "🧱" : cell === "home" ? "🏠" : cell === "nature" ? "🦌" : cell === "fire" ? "🔥" : "🌲"}</button>; }))}</div><div className="decision-footer"><span>{simulating ? "Simulando propagación…" : `${4-breaks.size} piezas disponibles`}</span><button className="primary" disabled={breaks.size < 3 || simulating} onClick={simulate}>{simulating ? "Simulando…" : "Iniciar simulación"}</button></div></section>;
}

function DetectiveGame({ finish }: { finish: (result: Result) => void }) {
  const levels = [["●","●","■","●","●"],["▲","▲","▲","△","▲"],["◆","◆","◈","◆","◆"]]; const odd = [2,3,2]; const [level,setLevel]=useState(0); const [correct,setCorrect]=useState(0); const started=useMemo(()=>Date.now(),[]);
  const choose=(index:number)=>{ const next=correct+(index===odd[level]?1:0); if(level===2){const seconds=Math.max(1,Math.round((Date.now()-started)/1000)); finish({score:clampScore(next*300+Math.max(0,100-seconds*4)),title:next===3?"Patrones detectados":"Sigue observando",metrics:[["Respuestas correctas",`${next}/3`],["Tiempo",`${seconds}s`],["Anomalía","Forma, relleno o combinación"]],explanation:"Un modelo de anomalías compara varias características y destaca observaciones poco habituales."});} else {setCorrect(next);setLevel(value=>value+1);}};
  return <section className="play-panel"><h2>Nivel {level+1} de 3</h2><p>Selecciona el elemento diferente.</p><div className="pattern-grid">{levels[level].map((value,index)=><button type="button" key={index} onClick={()=>choose(index)} aria-label={`Elemento ${index+1}`}>{value}</button>)}</div></section>;
}

function ChampionGame({ finish }: { finish: (result: Result) => void }) { const probabilities=championProbabilities(teams); const [selected,setSelected]=useState<number|null>(null); const [simulating,setSimulating]=useState(false); const finishAfter=useDelayedFinish(finish); const simulate=()=>{if(selected===null)return;setSimulating(true);const best=probabilities.indexOf(Math.max(...probabilities));finishAfter({score:selected===best?1000:720,title:selected===best?"Buena predicción":"Una alternativa era más probable",metrics:[["Equipo elegido",teams[selected].name],...teams.map((team,i)=>[team.name,`${probabilities[i]} victorias de 100`] as [string,string])],explanation:"La simulación repitió el torneo usando ataque, defensa y rendimiento reciente como señales."},900);}; return <section className={`play-panel ${simulating?"is-simulating":""}`}><h2>Elige al posible campeón</h2><div className="team-grid">{teams.map((team,index)=><button type="button" aria-pressed={selected===index} className={selected===index?"selected":""} onClick={()=>setSelected(index)} key={team.name}><strong>{team.name}</strong><span>Ataque {team.attack}</span><span>Defensa {team.defense}</span><span>Forma {team.form}</span></button>)}</div><div className="decision-footer"><span>{simulating?"Ejecutando 100 torneos…":selected===null?"Selecciona un equipo":`${teams[selected].name} es tu predicción`}</span><button className="primary" disabled={selected===null||simulating} onClick={simulate}>{simulating?"Simulando…":"Simular torneo"}</button></div></section>; }

function EnergyGame({ finish }: { finish: (result: Result) => void }) { const [active,setActive]=useState(()=>services.map(()=>true)); const total=energyTotal(services.map((service,index)=>({consumption:service.consumption,active:active[index]}))); const submit=()=>{const essentials=services.filter((service,index)=>service.essential&&active[index]).length;const score=clampScore(essentials*230+(total<=85?260:0)-(Math.max(0,total-85)*8));finish({score,title:essentials===3&&total<=85?"Ciudad en funcionamiento":"Revisa tus prioridades",metrics:[["Energía utilizada",`${total}/85`],["Servicios esenciales",`${essentials}/3`],["Apagones evitados",essentials]],explanation:"La capacidad bajó inesperadamente a 85 unidades. Los servicios esenciales aportan más valor social."});}; return <section className="play-panel"><h2>Evita el apagón</h2><div className={`energy-meter ${total>85?"over":""}`}><span style={{width:`${Math.min(100,total/85*100)}%`}}/><strong>{total} / 85</strong></div><div className="service-grid">{services.map((service,index)=><button type="button" aria-pressed={active[index]} className={active[index]?"active":""} key={service.name} onClick={()=>setActive(values=>values.map((value,i)=>i===index?!value:value))}><span>{service.icon}</span><strong>{service.name}</strong><small>{service.consumption} u · {service.essential?"Esencial":"Flexible"}</small></button>)}</div><button className="primary" onClick={submit}>Finalizar el día</button></section>; }

function WaitingGame({ finish }: { finish:(result:Result)=>void }) { const options=[42,67,54,88,73,96,61]; const [index,setIndex]=useState(0); const accept=()=>{const value=options[index],best=Math.max(...options);finish({score:clampScore(value/best*1000),title:value===best?"Elegiste la mejor opción":"Decisión tomada",metrics:[["Alternativa elegida",`${value} puntos`],["Mejor alternativa",`${best} puntos`],["Momento",`${index+1} de ${options.length}`],["Diferencia",best-value]],explanation:"No podías volver atrás: esperar daba acceso a nuevas opciones, pero también implicaba perder las anteriores."});}; return <section className="play-panel centered"><div className="step-dots" aria-label={`Opción ${index+1} de ${options.length}`}>{options.map((_,step)=><span className={step<=index?"active":""} key={step}/>)}</div><h2>Proyecto {index+1} de {options.length}</h2><div className="option-reveal" key={index}>🤖<strong>{options[index]}</strong><span>puntos de potencial</span></div><div className="action-row"><button className="primary" onClick={accept}>Aceptar</button><button className="secondary" disabled={index===options.length-1} onClick={()=>setIndex(value=>value+1)}>Seguir esperando</button></div></section>; }

function HousingGame({ finish }: { finish:(result:Result)=>void }) { const [value,setValue]=useState(500); const model=640; const submit=()=>{const diff=Math.abs(value-model);finish({score:clampScore(1000-diff*2.4),title:diff<=50?"Estimación muy cercana":"El modelo estimó otro rango",metrics:[["Tu estimación",`${value} unidades`],["Modelo",`${model} unidades`],["Diferencia",`${diff} unidades`],["Variables clave","Tamaño y transporte"]],explanation:"El modelo combinó 120 m², 3 habitaciones, transporte cercano, áreas verdes y estado de conservación."});}; return <section className="play-panel"><h2>Estima esta vivienda ficticia</h2><div className="house-card">🏠<ul><li>120 m² · 3 habitaciones</li><li>Transporte a 5 minutos</li><li>Áreas verdes cercanas</li><li>Centro a 8 km</li><li>Buen estado</li></ul></div><label className="price-slider">Tu estimación: <strong>{value} unidades</strong><input type="range" min="300" max="900" step="10" value={value} onChange={event=>setValue(Number(event.target.value))}/></label><button className="primary" onClick={submit}>Comparar con el modelo</button></section>; }

function SpaceGame({ finish }: { finish:(result:Result)=>void }) {
  const [participantTotal,setParticipantTotal]=useState<number | null>(null); const [participant,setParticipant]=useState(1); const [proposals,setProposals]=useState<Array<Set<number>>>([]); const [selected,setSelected]=useState(new Set<number>());
  const consensus=participantTotal !== null && participant>participantTotal; const weight=[...selected].reduce((sum,index)=>sum+spaceItems[index].weight,0); const utility=[...selected].reduce((sum,index)=>sum+spaceItems[index].utility,0); const optimum=optimalKnapsack(spaceItems,25);
  const toggle=(index:number)=>setSelected(current=>{const next=new Set(current);next.has(index)?next.delete(index):next.add(index);return next;});
  const confirm=()=>{setProposals(current=>[...current,new Set(selected)]);setSelected(new Set());setParticipant(value=>value+1);};
  const submit=()=>{const individualUtilities=proposals.map(proposal=>[...proposal].reduce((sum,index)=>sum+spaceItems[index].utility,0));const bestIndividual=Math.max(...individualUtilities);finish({score:clampScore(utility/optimum*1000),title:utility>=bestIndividual?"El consenso mejoró la decisión":"La mejor propuesta individual era superior",metrics:[["Peso utilizado",`${weight}/25`],["Utilidad grupal",utility],["Mejor decisión individual",bestIndividual],["Solución óptima",optimum]],explanation:`El consenso ${utility>=bestIndividual?"mejoró o igualó":"empeoró"} la mejor propuesta individual. Comparen qué criterios cambiaron.`});};
  if (participantTotal === null) return <section className="play-panel"><h2>¿Cuántas personas participan?</h2><p>Las decisiones individuales permanecerán ocultas hasta comenzar el consenso.</p><div className="participant-options">{[2,3,4,5].map(total=><button className="secondary" type="button" onClick={()=>setParticipantTotal(total)} key={total}>{total} participantes</button>)}</div></section>;
  return <section className="play-panel"><h2>{consensus?"Etapa 2: decisión por consenso":`Etapa 1: participante ${participant} de ${participantTotal}`}</h2><p>{consensus?"Las propuestas ya están visibles. Conversen y creen la carga final.":"Elige en privado y confirma. La selección se ocultará antes del siguiente turno."} Capacidad restante: <strong>{25-weight}</strong></p>
    {consensus&&<div className="proposal-summary">{proposals.map((proposal,index)=><span key={index}>Propuesta {index+1}: {[...proposal].map(item=>spaceItems[item].name).join(", ")}</span>)}</div>}
    <div className="space-grid">{spaceItems.map((item,index)=><button type="button" aria-pressed={selected.has(index)} className={selected.has(index)?"selected":""} onClick={()=>toggle(index)} key={item.name}><span>{item.icon}</span><strong>{item.name}</strong><small>{item.weight} kg · utilidad {item.utility}</small></button>)}</div>
    <button className="primary" disabled={weight>25||selected.size===0} onClick={consensus?submit:confirm}>{weight>25?"Exceso de peso":consensus?"Despegar":"Confirmar y ocultar"}</button></section>;
}

function HospitalGame({ finish }: { finish:(result:Result)=>void }) { const impacts=hospitals.map(hospitalImpact); const best=impacts.indexOf(Math.max(...impacts)); const [selected,setSelected]=useState<number|null>(null); const choose=()=>{if(selected===null)return;finish({score:selected===best?1000:680,title:selected===best?"Recurso bien asignado":"Había una alternativa de mayor impacto",metrics:[["Hospital seleccionado",hospitals[selected].name],["Personas atendidas",impacts[selected]],["Presión inicial",`${hospitals[selected].waiting} esperando`],["Mejor alternativa",hospitals[best].name]],explanation:"El equipo adicional funciona mejor donde coinciden demanda, camas y personal suficiente para utilizarlo."});}; return <section className="play-panel"><h2>Asigna una unidad de apoyo</h2><p>Selecciona el hospital donde permitirá atender a más personas.</p><div className="hospital-grid">{hospitals.map((hospital,index)=><button type="button" aria-pressed={selected===index} className={selected===index?"selected":""} onClick={()=>setSelected(index)} key={hospital.name}><span>🏥</span><strong>{hospital.name}</strong><small>{hospital.waiting} esperando</small><small>{hospital.beds} camas · {hospital.staff} funcionarios</small></button>)}</div><div className="decision-footer"><span>{selected===null?"Unidad disponible":`Destino: ${hospitals[selected].name}`}</span><button className="primary" disabled={selected===null} onClick={choose}>Asignar recurso</button></div></section>; }
