import { useState } from "react";
import { Copy, LogOut, Users, X } from "lucide-react";
import { useMultiplayer } from "../multiplayer/MultiplayerContext";

export function MultiplayerPanel({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { room, playerId, busy, error, createRoom, joinRoom, leaveRoom } = useMultiplayer(); const [mode, setMode] = useState<"menu"|"create"|"join">("menu"); const [name,setName]=useState(""); const [code,setCode]=useState("");
  if (!open) return null;
  const submit = async () => { try { if (mode === "create") await createRoom(name); else await joinRoom(code, name); } catch {} };
  return <div className="multiplayer-overlay" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="multiplayer-panel" role="dialog" aria-modal="true" aria-label="Partida multijugador"><button className="modal-close" onClick={onClose} aria-label="Cerrar"><X/></button>
    {room ? <><p className="eyebrow"><Users size={16}/> Sala multijugador</p><h2>Código de la partida</h2><button className="room-code" onClick={()=>navigator.clipboard.writeText(room.code)}>{room.code}<Copy/></button><p>Comparte estas 6 letras. La tabla se actualiza automáticamente.</p><div className="room-players">{Object.values(room.players).map(player=><span key={player.id}><i>{player.id===room.hostId?"★":"●"}</i>{player.name}{player.id===playerId&&<small>Tú</small>}</span>)}</div>{room.hostId===playerId?<p className="room-hint">Elige cualquier juego del catálogo para iniciar la competencia.</p>:<p className="room-hint">Esperando que quien creó la sala elija un juego…</p>}<button className="secondary" onClick={()=>{leaveRoom();setMode("menu");}}><LogOut/>Salir de la sala</button></> : mode === "menu" ? <><p className="eyebrow"><Users size={16}/> Competencia en vivo</p><h2>Jueguen desde distintos dispositivos</h2><p>Cada persona juega el mismo desafío y sus puntajes aparecen en una tabla común.</p><button className="primary" onClick={()=>setMode("create")}>Crear una partida</button><button className="secondary" onClick={()=>setMode("join")}>Unirme con un código</button></> : <><p className="eyebrow">{mode==="create"?"Nueva competencia":"Entrar a una competencia"}</p><h2>{mode==="create"?"¿Cómo te llamas?":"Ingresa tus datos"}</h2><label>Nombre o apodo<input autoFocus maxLength={20} value={name} onChange={e=>setName(e.target.value)} placeholder="Ej: Camila"/></label>{mode==="join"&&<label>Código de 6 letras<input className="code-input" maxLength={6} value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z]/g,""))} placeholder="ABCDEF"/></label>}{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy||name.trim().length<2||(mode==="join"&&code.length!==6)} onClick={submit}>{busy?"Conectando…":mode==="create"?"Crear y obtener código":"Entrar a la partida"}</button><button className="text-button" onClick={()=>setMode("menu")}>Volver</button></>}
  </section></div>;
}
